"""baseline — full Atlas Argus schema plus database-level doctrine guards
(append-only audit trigger, human-readable ID sequences).

Revision ID: 0001
Revises:
Create Date: 2026-07-11 10:36:57.403679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Frozen here: historical migrations must not change when runtime guard lists
# gain new tables, functions, or sequences.
AUDIT_GUARD_SQL = """
CREATE OR REPLACE FUNCTION forbid_audit_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'audit_event is append-only: % rejected', TG_OP;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS trg_audit_append_only ON audit_event;
CREATE TRIGGER trg_audit_append_only BEFORE UPDATE OR DELETE ON audit_event
FOR EACH ROW EXECUTE FUNCTION forbid_audit_mutation();
"""
ID_SEQUENCES = (
    "claim_id_seq",
    "conflict_id_seq",
    "section_id_seq",
    "source_id_seq",
)

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_file',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('aircraft', sa.String(), nullable=False),
    sa.Column('accident_date', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('matter_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('docket_ref', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviewer',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.CheckConstraint("role IN ('Accident Reconstruction Expert', 'Claims Reviewer', 'Safety Investigator', 'Senior Aviation Counsel')", name='ck_reviewer_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_event',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('actor_role', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('subject_type', sa.String(), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=False),
    sa.Column('previous_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('report_eligibility_changed', sa.Boolean(), nullable=False),
    sa.CheckConstraint("subject_type IN ('claim', 'conflict', 'export', 'report_section', 'source')", name='ck_audit_subject'),
    sa.ForeignKeyConstraint(['case_id'], ['case_file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seq')
    )
    op.create_table('auth_session',
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('reviewer_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_id'], ['reviewer.id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_table('report_section',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('paragraph_ref', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('claim_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_section_paragraph_ref', 'report_section', ['case_id', sa.literal_column('lower(paragraph_ref)')], unique=True)
    op.create_table('source_document',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('custodian', sa.String(), nullable=False),
    sa.Column('docket_ref', sa.String(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('privilege_status', sa.String(), nullable=False),
    sa.Column('custody', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("privilege_status IN ('attorney_client', 'confidential', 'public', 'restricted', 'work_product')", name='ck_source_privilege'),
    sa.CheckConstraint("type IN ('atc_transcript', 'deposition', 'expert_report', 'flight_recorder', 'internal_memo', 'official_report', 'operational_record', 'weather_data')", name='ck_source_type'),
    sa.ForeignKeyConstraint(['case_id'], ['case_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source_document_id', sa.String(), nullable=False),
    sa.Column('page_ref', sa.String(), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_quality', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('privilege_status', sa.String(), nullable=False),
    sa.Column('report_eligibility', sa.String(), nullable=False),
    sa.Column('reviewer', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("evidence_quality IN ('corroborated', 'primary', 'secondary', 'uncorroborated')", name='ck_claim_quality'),
    sa.CheckConstraint("privilege_status IN ('attorney_client', 'confidential', 'public', 'restricted', 'work_product')", name='ck_claim_privilege'),
    sa.CheckConstraint("report_eligibility IN ('blocked_by_conflict', 'eligible', 'excluded', 'needs_review', 'privileged')", name='ck_claim_eligibility'),
    sa.CheckConstraint("status IN ('disputed', 'escalated', 'preserved', 'rejected', 'superseded', 'supported', 'unreviewed')", name='ck_claim_status'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_claim_confidence'),
    sa.ForeignKeyConstraint(['case_id'], ['case_file.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conflict',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('claim_a_id', sa.String(), nullable=False),
    sa.Column('claim_b_id', sa.String(), nullable=False),
    sa.Column('conflict_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("conflict_type IN ('factual', 'interpretation', 'source_reliability', 'timeline')", name='ck_conflict_type'),
    sa.CheckConstraint("severity IN ('critical', 'high', 'low', 'medium')", name='ck_conflict_severity'),
    sa.CheckConstraint("status IN ('accepted_claim_a', 'accepted_claim_b', 'closed', 'escalated', 'preserved_both', 'source_unreliable', 'unresolved')", name='ck_conflict_status'),
    sa.CheckConstraint('claim_a_id <> claim_b_id', name='ck_conflict_distinct_claims'),
    sa.ForeignKeyConstraint(['case_id'], ['case_file.id'], ),
    sa.ForeignKeyConstraint(['claim_a_id'], ['claim.id'], ),
    sa.ForeignKeyConstraint(['claim_b_id'], ['claim.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_decision',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conflict_id', sa.String(), nullable=False),
    sa.Column('decision_type', sa.String(), nullable=False),
    sa.Column('selected_claim_id', sa.String(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('reviewer_name', sa.String(), nullable=False),
    sa.Column('reviewer_role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('previous_status', sa.String(), nullable=False),
    sa.Column('new_status', sa.String(), nullable=False),
    sa.Column('report_impact', sa.Text(), nullable=False),
    sa.CheckConstraint("decision_type IN ('accept_claim_a', 'accept_claim_b', 'escalate', 'mark_source_unreliable', 'mark_unresolved', 'preserve_both')", name='ck_decision_type'),
    sa.CheckConstraint("new_status IN ('accepted_claim_a', 'accepted_claim_b', 'closed', 'escalated', 'preserved_both', 'source_unreliable', 'unresolved')", name='ck_decision_new_status'),
    sa.CheckConstraint("previous_status IN ('accepted_claim_a', 'accepted_claim_b', 'closed', 'escalated', 'preserved_both', 'source_unreliable', 'unresolved')", name='ck_decision_prev_status'),
    sa.CheckConstraint("reviewer_role IN ('Accident Reconstruction Expert', 'Claims Reviewer', 'Safety Investigator', 'Senior Aviation Counsel')", name='ck_decision_role'),
    sa.ForeignKeyConstraint(['conflict_id'], ['conflict.id'], ),
    sa.ForeignKeyConstraint(['selected_claim_id'], ['claim.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Database-level doctrine the ORM cannot express: audit_event is
    # append-only, and human-readable ids come from race-free sequences.
    op.execute(AUDIT_GUARD_SQL)
    for sequence in ID_SEQUENCES:
        op.execute(f"CREATE SEQUENCE IF NOT EXISTS {sequence}")


def downgrade() -> None:
    for sequence in ID_SEQUENCES:
        op.execute(f"DROP SEQUENCE IF EXISTS {sequence}")
    op.execute("DROP FUNCTION IF EXISTS forbid_audit_mutation() CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_decision')
    op.drop_table('conflict')
    op.drop_table('claim')
    op.drop_table('source_document')
    op.drop_index('ux_section_paragraph_ref', table_name='report_section')
    op.drop_table('report_section')
    op.drop_table('auth_session')
    op.drop_table('audit_event')
    op.drop_table('reviewer')
    op.drop_table('case_file')
    # ### end Alembic commands ###
